---
# tasks file for nginx

- name: Install
  become: yes
  apt: name=nginx state=latest

- name: Start
  become: yes
  service: name=nginx state=started enabled=true

- name: Supprimer default.conf
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: nginx reload

- name: création du dossier
  file: path=/home/{{ user}}/{{ domain}} state=directory owner={{ user }}

- name: lier {{ domain }} vers www
  become: yes
  file: src=/home/{{ user}}/{{ domain}} dest=/var/www/{{ domain }} state=link

- name: Création de la configuration nginx
  become: yes
  template: src=templates/nginx.j2 dest=/etc/nginx/sites-available/{{ domain }}
  notify: nginx reload

- name: activation du domaine {{ domain }}
  become: yes
  file: src=/etc/nginx/sites-available/{{ domain }} dest=/etc/nginx/sites-enabled/{{ domain }} state=link
  notify: nginx reload

# - lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp='date.timezone[\s]?=' line='date.timezone = {{ php_timezone }}'

# # Que l'on utilisera Ensuite
# - name: Installation du package {{ item }}
#   apt: name={{ item }} state=latest
#   with_items: php_packages