---
# tasks file for nginx

- name: Install
  become: yes
  apt: name=nginx state=latest

- name: Start
  become: yes
  service: name=nginx state=started enabled=true

- name: Supprimer default.conf
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: nginx reload

- name: Configuration de PHP
  become: yes
  include: php.yml

- name: COnfiguration des sites
  include: site.yml
  with_items: "{{ domains }}"

# - lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp='date.timezone[\s]?=' line='date.timezone = {{ php_timezone }}'

# # Que l'on utilisera Ensuite
# - name: Installation du package {{ item }}
#   apt: name={{ item }} state=latest
#   with_items: php_packages