# ce fichier est un playbook
---
- name: Installation des serveurs web
  hosts: webservers
  remote_user: root
  vars:
    user: prod
    domains: 
      - local.dev
      - local2.dev
    backup_root: backup
    ansible_network_os: ios
    ansible_connection: network_cli

  vars_files:
    - vars/spoilers.yml

  roles:
    - backup
    - utils
    - user
    - nginx

  tasks: 
  - name: Put the spoiler text in the tmp directory on the remote server.
    copy:
      content="{{spoiler_text}}"
      dest=/tmp/spoiler_text.txt

