# ce fichier est un playbook
---
- name: Installation des serveurs web
  hosts: webservers
  remote_user: root
  vars:
    user: prod
    domain: local.dev

  vars_files:
    - vars/spoilers.yml

  roles:
    - utils
    - user
    - nginx

  tasks: 
  - name: Put the spoiler text in the tmp directory on the remote server.
    copy:
      content="{{spoiler_text}}"
      dest=/tmp/spoiler_text.txt

