---
# defaults file for nginx
php_timezone: Europe/Paris
php_upload_max_filezise: "20M"
php_post_max_filezise: "20M"
php_memory_limit: "1024M"

php_packages:
  - php7.0
  - php7.0-common
  - php7.0-cli
  - php7.0-intl
  - php7.0-curl
  - php7.0-cgi
  - php7.0-fpm
  - php7.0-mcrypt
  - php7.0-mysql
  - php7.0-gd